### ISSUE TITLE
Password encrypted key

### ISSUE THREAD

**Issue by hamsterwoede** [bikibird/JournalSixSource#2]
Hi, 

It might just be my inexperience with Visual basic (haven´t touched it since 2002), but when I try to open the project, it keeps asking for a key to use with JournalSix.pfx. Is this key something you can share?

Thank you so much for sharing this software. It has helped me both the inner working of the console a lot better, as well as making me a better machine knitter. Although I still have a lot of practice to do.

best wishes,

Martin Kloos

**Comment by bikibird** [comment]
I apologize for taking so long to get back to you on this.  For some reason I missed this.  I believe the key is **jasminegreenteapot**

**Comment by hamsterwoede** [comment]
Thank you so much! Hopefully I'll be able to build from source now :-)

**Comment by bikibird** [comment]
Be sure to grab a fresh copy of the repository.  I believe I have all the files uploaded now.

**Comment by hamsterwoede** [comment]
Thank you, I will :-)
