### ISSUE TITLE
Newer version?

### ISSUE THREAD

**Issue by Pacamania** [bikibird/JournalSixSource#3]
I have a purchased version of this from years ago, version 9.  Is this source code a newer version and is there any benefit to moving to it from my other version?
Also, your online card reader technique generator at passappal.com is no longer accessible(site registration expired), and I'm wondering if this tool is available elsewhere or will be again?
Thanks,
Brian

**Comment by bikibird** [comment]
This is version 9.  So you are current.  I shut down the PassapPal site. However you can everything from the old site here: [http://bikibird.com/PassapPal/](http://bikibird.com/PassapPal/).  Eventually I plan to update the CRT generator and post it at my general knitting site, [http://infiniteloopknitting.com/](http://infiniteloopknitting.com/)
